#include "theme/fastfetch_sync.h"

#include <stdlib.h>

#include "config/paths.h"
#include "exec/process.h"
#include "theme/color_scheme.h"
#include "util/fsutil.h"
#include "util/strbuf.h"
#include "util/xalloc.h"

static char *fastfetch_config_path(void) {
    char *dir = config_dir();
    if (!dir) {
        return NULL;
    }
    char *path = join_path(dir, "fastfetch.jsonc");
    free(dir);
    return path;
}

bool fastfetch_sync_write(const Theme *theme, char **out_path) {
    char *path = fastfetch_config_path();
    if (out_path) {
        *out_path = path ? xstrdup(path) : NULL;
    }
    if (!path) {
        return false;
    }

    TermColorScheme cs;
    color_scheme_build(theme, &cs);

    StrBuf sb;
    strbuf_init(&sb);
    strbuf_append(&sb, "// Generated by calm-shell (`calm sync`) -- edits here are overwritten on\n"
                        "// the next sync. Change the active Calm-shell theme instead.\n"
                        "{\n"
                        "  \"$schema\": \"https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json\",\n"
                        "  \"logo\": {\n"
                        "    \"type\": \"small\",\n"
                        "    \"padding\": { \"top\": 1, \"left\": 1, \"right\": 2 },\n"
                        "    \"color\": {\n");
    for (int i = 1; i <= 6; i++) {
        char *line = xsprintf("      \"%d\": \"%s\",\n", i, cs.ansi[i]);
        strbuf_append(&sb, line);
        free(line);
    }
    char *line = xsprintf("      \"7\": \"%s\",\n      \"8\": \"%s\"\n    }\n  },\n", cs.foreground, cs.ansi[8]);
    strbuf_append(&sb, line);
    free(line);

    strbuf_append(&sb, "  \"display\": {\n"
                        "    \"separator\": \" \",\n"
                        "    \"color\": {\n");
    line = xsprintf("      \"keys\": \"%s\",\n      \"title\": \"%s\"\n    }\n  },\n", cs.ansi[4], cs.cursor);
    strbuf_append(&sb, line);
    free(line);

    strbuf_append(&sb, "  \"modules\": [\n"
                        "    \"title\",\n"
                        "    \"separator\",\n"
                        "    \"os\",\n"
                        "    \"host\",\n"
                        "    \"kernel\",\n"
                        "    \"uptime\",\n"
                        "    \"packages\",\n"
                        "    \"shell\",\n"
                        "    \"terminal\",\n"
                        "    \"cpu\",\n"
                        "    \"gpu\",\n"
                        "    \"memory\",\n"
                        "    \"disk\",\n"
                        "    \"break\",\n"
                        "    \"colors\"\n"
                        "  ]\n"
                        "}\n");

    char *contents = strbuf_take(&sb);
    bool ok = overwrite_file(path, contents);
    free(contents);
    color_scheme_free(&cs);
    free(path);
    return ok;
}

bool fastfetch_run(const char *config_path) {
    if (!process_command_exists("fastfetch")) {
        return true; /* not installed: nothing to show, not an error */
    }
    char *const argv[] = {"fastfetch", "--config", (char *)config_path, NULL};
    int status = 0;
    return process_run_foreground(argv, &status);
}
