#include "config/profile.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "config/calm_serialize.h"
#include "config/paths.h"
#include "config/plugin_loader.h"
#include "config/scaffold.h"
#include "exec/process.h"
#include "theme/sync.h"
#include "theme/theme.h"
#include "util/fsutil.h"
#include "util/strbuf.h"
#include "util/strlist.h"
#include "util/xalloc.h"

/* Every section a profile file is allowed to pass through verbatim
 * into profile_active.calm, in a fixed, deliberate order (independent
 * of the order they appear in the profile file -- calmconf sections
 * are a flat namespace, so re-ordering them on the way out changes
 * nothing observable, and a fixed order makes generated output diffable
 * between activations). `[profile]` (activation-only metadata) and
 * `[startup]` (run-once commands) are deliberately absent -- neither
 * belongs in a file that's re-included on every future shell launch.
 * `[plugins]` is also absent here even though a profile can specify
 * one: it's handled separately, by actually driving the plugin loader
 * (see profile_apply()) rather than being passed through as inert
 * text the way the other sections are. */
static const char *const PASSTHROUGH_SECTIONS[] = {
    "shell",  "prompt",  "environment", "directory", "directory.aliases",
    "history", "keyboard", "keyboard.bindings", "terminal", "appearance",
    "sync",   "aliases", "functions",
};
#define PASSTHROUGH_COUNT (sizeof(PASSTHROUGH_SECTIONS) / sizeof(PASSTHROUGH_SECTIONS[0]))

bool profile_load(const char *name, Profile *out, char **err_msg) {
    char *dir = profiles_dir();
    if (!dir) {
        if (err_msg) {
            *err_msg = xstrdup("could not resolve ~/.config/calm-shell/profiles");
        }
        return false;
    }
    char *filename = xsprintf("%s.calm", name);
    char *path = join_path(dir, filename);
    free(filename);
    free(dir);

    CalmDocument doc;
    if (!calm_parse_file(path, &doc, err_msg)) {
        free(path);
        return false;
    }
    free(path);

    out->name = xstrdup(name);
    out->doc = doc;
    return true;
}

void profile_free(Profile *p) {
    free(p->name);
    p->name = NULL;
    calm_document_free(&p->doc);
}

/* Mirrors theme_cmd.c's theme_set(): writes the active-theme marker
 * and immediately re-syncs the terminal emulator + Fastfetch, so a
 * profile switch's theme change is visible right away rather than
 * only on the next shell launch. Kept as its own small function here
 * (instead of exposing theme_cmd.c's static theme_set) since the two
 * call sites want slightly different output -- this one folds its
 * summary into profile_apply()'s own printed lines. */
static bool apply_profile_theme(const char *theme_name) {
    Theme t;
    if (!theme_load(theme_name, &t)) {
        return false;
    }
    theme_free(&t);

    char *marker = active_theme_marker_file();
    if (!marker) {
        return false;
    }
    bool ok = overwrite_file(marker, theme_name);
    free(marker);
    if (!ok) {
        return false;
    }

    char *cfg_path = config_file();
    CalmDocument cfg;
    char *cfg_err = NULL;
    if (cfg_path && calm_parse_file(cfg_path, &cfg, &cfg_err)) {
        Theme active;
        if (theme_load(theme_name, &active)) {
            ThemeSyncResult result;
            theme_sync_apply(&active, &cfg, &result);
            theme_sync_result_free(&result);
            theme_free(&active);
        }
        calm_document_free(&cfg);
    }
    free(cfg_err);
    free(cfg_path);
    return true;
}

/* overwrite_file() doesn't append a trailing newline itself -- the
 * active-theme marker (a bare name, no `.calm` structure to speak of)
 * wants one so `cat`/manual inspection behaves, matching theme_set()'s
 * own fprintf(f, "%s\n", name) shape. */
static bool overwrite_file_line(const char *path, const char *line) {
    char *with_newline = xsprintf("%s\n", line);
    bool ok = overwrite_file(path, with_newline);
    free(with_newline);
    return ok;
}

bool profile_apply(const Profile *p, char **warnings) {
    if (warnings) {
        *warnings = NULL;
    }
    if (!ensure_scaffold()) {
        return false;
    }

    StrBuf sb;
    strbuf_init(&sb);
    strbuf_append(&sb, "# Generated by `calm profile ");
    strbuf_append(&sb, p->name);
    strbuf_append(&sb, "` -- do not edit by hand, your changes will be\n"
                        "# overwritten the next time a profile is applied.\n\n");
    for (size_t i = 0; i < PASSTHROUGH_COUNT; i++) {
        calm_serialize_section(&sb, &p->doc, PASSTHROUGH_SECTIONS[i]);
    }
    char *generated = strbuf_take(&sb);

    char *active_path = profile_active_file();
    bool wrote = active_path && overwrite_file(active_path, generated);
    free(active_path);
    free(generated);
    if (!wrote) {
        return false;
    }

    const char *theme_name = calm_document_get_str(&p->doc, "profile", "theme");
    if (theme_name && theme_name[0] != '\0') {
        apply_profile_theme(theme_name); /* best-effort, matching theme_set()'s own tolerance */
    }

    /* A profile that specifies `[plugins] enabled = [...]` replaces
     * the enabled-plugin set outright (not a merge) -- switching to a
     * profile is meant to put you in a known, deterministic
     * environment, the same reasoning `[environment]`/`[aliases]`
     * pass-through already follows. A profile that omits `[plugins]`
     * entirely leaves whatever was already enabled untouched. */
    const CalmValue *plugins_list = calm_document_get(&p->doc, "plugins", "enabled");
    if (plugins_list && plugins_list->type == CALM_LIST) {
        StrList names;
        strlist_init(&names);
        for (size_t i = 0; i < plugins_list->as.list.count; i++) {
            if (plugins_list->as.list.items[i].type == CALM_STRING) {
                strlist_add(&names, plugins_list->as.list.items[i].as.string);
            }
        }
        plugin_loader_set_enabled(&names); /* best-effort, matching the theme apply above */
        strlist_free(&names);
    }
    char *plugin_warnings = NULL;
    plugin_loader_sync(&plugin_warnings);
    free(plugin_warnings); /* profile_apply's own warnings are about startup commands; a plugin load
                             * issue here would already have been visible from `calm plugin enable` */

    char *marker = active_profile_marker_file();
    if (marker) {
        overwrite_file_line(marker, p->name);
        free(marker);
    }

    /* Startup commands run once, right now -- there's nothing in
     * profile_active.calm that would replay them on a future launch
     * (see profile.h). Each runs through /bin/sh -c, the same
     * dispatch shell/execute.c uses for anything that isn't a bare
     * builtin, so pipes/redirection/&&/;  all work exactly as typed. */
    const CalmValue *startup = calm_document_get(&p->doc, "startup", "commands");
    if (startup && startup->type == CALM_LIST && process_command_exists("/bin/sh")) {
        StrBuf failed;
        strbuf_init(&failed);
        for (size_t i = 0; i < startup->as.list.count; i++) {
            const CalmValue *item = &startup->as.list.items[i];
            if (item->type != CALM_STRING) {
                continue;
            }
            char *argv_sh[] = {(char *)"/bin/sh", (char *)"-c", item->as.string, NULL};
            int status = 0;
            bool spawned = process_run_foreground(argv_sh, &status);
            if (!spawned || status != 0) {
                strbuf_append(&failed, "  startup command failed: ");
                strbuf_append(&failed, item->as.string);
                strbuf_append_char(&failed, '\n');
            }
        }
        char *failed_str = strbuf_take(&failed);
        if (failed_str[0] != '\0' && warnings) {
            *warnings = failed_str;
        } else {
            free(failed_str);
        }
    }

    return true;
}

char *profile_active_name(void) {
    char *marker = active_profile_marker_file();
    if (!marker) {
        return NULL;
    }
    char *content = read_file_to_string(marker);
    free(marker);
    if (!content) {
        return NULL;
    }
    char *nl = strchr(content, '\n');
    if (nl) {
        *nl = '\0';
    }
    if (content[0] == '\0') {
        free(content);
        return NULL;
    }
    return content;
}
