#include "config/scaffold.h"

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "config/paths.h"
#include "util/fsutil.h"
#include "util/xalloc.h"

static bool write_file_if_missing(const char *path, const char *contents) {
    if (path_exists(path)) {
        return true; /* already exists, leave user edits alone */
    }
    FILE *f = fopen(path, "w");
    if (!f) {
        return false;
    }
    size_t len = strlen(contents);
    bool ok = fwrite(contents, 1, len, f) == len;
    fclose(f);
    return ok;
}

static const char *default_config_calm(void) {
    return
        "# Calm-shell configuration\n"
        "# Full format guide: docs/CONFIGURATION.md in the calm-shell repo.\n"
        "#\n"
        "# This file is the entry point only -- each concern lives in its own\n"
        "# topic file (environment, directory, history, keyboard, terminal,\n"
        "# aliases, functions), included below.\n"
        "\n"
        "[shell]\n"
        "theme = \"calm-lavender\"\n"
        "greeting = true\n"
        "\n"
        "[prompt]\n"
        "show_git = true\n"
        "icon = \"\xF0\x9F\x8C\x99\"\n"
        "\n"
        "include \"environment.calm\"\n"
        "include \"directory.calm\"\n"
        "include \"history.calm\"\n"
        "include \"keyboard.calm\"\n"
        "include \"terminal.calm\"\n"
        "include \"aliases.calm\"\n"
        "include \"functions.calm\"\n"
        "\n"
        "# Generated by `calm plugin enable`/`disable` (and refreshed on every\n"
        "# shell startup) -- included before profile_active.calm below, so a\n"
        "# profile's own settings still win over a plugin's if they collide.\n"
        "# Do not edit this include line or plugins_active.calm by hand; both\n"
        "# are managed by the plugin system. See docs/CONFIGURATION.md.\n"
        "include \"plugins_active.calm\"\n"
        "\n"
        "# Generated by `calm profile <name>` -- always included last, so an\n"
        "# active profile's settings win over the topic files above (`calmconf`\n"
        "# lets a later definition of the same key overwrite an earlier one).\n"
        "# Do not edit this include line or profile_active.calm by hand; both\n"
        "# are managed by the profile system. See docs/CONFIGURATION.md.\n"
        "include \"profile_active.calm\"\n";
}

static const char *default_profile_active_calm(void) {
    return
        "# Generated by `calm profile <name>` -- do not edit by hand, your\n"
        "# changes will be overwritten the next time a profile is applied.\n"
        "# Empty until a profile has been activated at least once.\n";
}

static const char *default_plugins_active_calm(void) {
    return
        "# Generated by `calm plugin enable`/`disable` -- do not edit by hand,\n"
        "# your changes will be overwritten the next time a plugin is\n"
        "# (de)activated or a new shell session starts. Empty until a plugin\n"
        "# has been enabled at least once.\n";
}

static const char *default_plugins_calm(void) {
    return
        "# Which installed plugins (~/.config/calm-shell/plugins/<name>/) are\n"
        "# currently active. Managed by `calm plugin enable`/`disable` --\n"
        "# editing this list by hand works too, but won't take effect until\n"
        "# the next `calm plugin enable`/`disable` or shell session (or run\n"
        "# `calm repair` to refresh plugins_active.calm immediately).\n"
        "enabled = []\n";
}

static const char *default_environment_calm(void) {
    return
        "# Environment variables Calm-shell exports on launch\n"
        "\n"
        "[environment]\n"
        "EDITOR = \"nvim\"\n"
        "PAGER = \"less\"\n"
        "LANG = \"en_US.UTF-8\"\n";
}

static const char *default_directory_calm(void) {
    return
        "# Directory navigation behavior and shortcuts\n"
        "\n"
        "[directory]\n"
        "# Typing a bare directory name (no spaces, no other command) cds into it.\n"
        "auto_cd = true\n"
        "# How many entries pushd/popd/dirs remember; oldest is dropped first.\n"
        "dir_stack_size = 20\n"
        "\n"
        "[directory.aliases]\n"
        "\"..\" = \"cd ..\"\n"
        "\"...\" = \"cd ../..\"\n"
        "\"....\" = \"cd ../../..\"\n"
        "\"-\" = \"cd -\"\n";
}

static const char *default_history_calm(void) {
    return
        "# Shell history behavior\n"
        "\n"
        "[history]\n"
        "# Max entries kept in memory and in the history file; oldest entries\n"
        "# are dropped first once the count is exceeded.\n"
        "size = 10000\n"
        "# A command identical to the immediately preceding one is not added\n"
        "# again -- keeps repeated `ls`/`git status` runs from cluttering\n"
        "# Ctrl+R search and Up-arrow recall.\n"
        "ignore_dups = true\n"
        "# Not wired yet -- history is per-session (one file per running\n"
        "# calm, not merged live across concurrently open sessions).\n"
        "share_across_sessions = true\n";
}

static const char *default_keyboard_calm(void) {
    return
        "# Keybindings\n"
        "\n"
        "[keyboard]\n"
        "# \"emacs\" or \"vi\" -- switches the line editor's editing mode.\n"
        "edit_mode = \"emacs\"\n"
        "\n"
        "# Not wired yet -- these four happen to already match the line\n"
        "# editor's built-in emacs defaults, so they're accurate as\n"
        "# documentation, but changing a value here won't remap anything.\n"
        "[keyboard.bindings]\n"
        "\"ctrl+r\" = \"history-search-backward\"\n"
        "\"ctrl+a\" = \"beginning-of-line\"\n"
        "\"ctrl+e\" = \"end-of-line\"\n"
        "\"alt+backspace\" = \"backward-kill-word\"\n";
}

static const char *default_terminal_calm(void) {
    return
        "# Terminal integration behavior\n"
        "\n"
        "[terminal]\n"
        "# Sets the terminal tab/window title to \"calm -- <cwd>\" each prompt.\n"
        "set_title = true\n"
        "# Rings the terminal bell on calm's own errors (bad cd/pushd/popd\n"
        "# target, a command that couldn't be spawned at all) -- not on every\n"
        "# failing command's nonzero exit status.\n"
        "bell = false\n"
        "# Whether the prompt/editor emit 24-bit ANSI color at all. Also\n"
        "# disabled automatically when $NO_COLOR is set, per no-color.org.\n"
        "truecolor = true\n"
        "\n"
        "# Non-color appearance, shared across every terminal emulator `calm\n"
        "# sync` writes a theme file for -- font, cursor, transparency,\n"
        "# padding, and window decorations. Colors themselves come from the\n"
        "# active theme's own [terminal] section, not from here.\n"
        "[appearance]\n"
        "font_family        = \"monospace\"\n"
        "font_size          = 12\n"
        "# \"beam\", \"block\", or \"underline\".\n"
        "cursor_style       = \"beam\"\n"
        "cursor_blink       = true\n"
        "# 1.0 = fully opaque, down to 0.0 = fully transparent.\n"
        "opacity            = 1.0\n"
        "# Uniform cell padding in pixels.\n"
        "padding            = 8\n"
        "window_decorations = true\n"
        "\n"
        "# Controls `calm sync` -- detecting the host terminal emulator and\n"
        "# regenerating its theme file, regenerating Fastfetch's config, and\n"
        "# pushing the theme out to every other app calm-shell knows how to\n"
        "# theme (Cava, btop, Yazi, Neovim, Helix, Hyprland, Waybar, Wofi,\n"
        "# Fuzzel) -- every time the active theme changes and once per new\n"
        "# session.\n"
        "[sync]\n"
        "sync_terminal        = true\n"
        "sync_fastfetch       = true\n"
        "sync_apps            = true\n"
        "run_fastfetch_on_start = true\n"
        "# Force detection to a specific emulator (\"kitty\", \"alacritty\",\n"
        "# \"wezterm\", \"foot\", \"ghostty\", \"konsole\", \"gnome-terminal\") --\n"
        "# useful under tmux/ssh, where the real host emulator's environment\n"
        "# variables don't survive the hop. Empty string means auto-detect.\n"
        "terminal_override    = \"\"\n";
}

static const char *default_aliases_calm(void) {
    return
        "# Calm-shell aliases -- key = command\n"
        "\n"
        "[aliases]\n"
        "ll = \"ls -la\"\n"
        "gs = \"git status\"\n"
        "gc = \"git commit\"\n"
        "gp = \"git push\"\n";
}

static const char *default_functions_calm(void) {
    return
        "# Calm-shell functions -- triple-quoted blocks hold raw shell bodies\n"
        "\n"
        "[functions]\n"
        "mkcd = \"\"\"\n"
        "mkdir -p \"$1\" && cd \"$1\"\n"
        "\"\"\"\n";
}

const char *default_lavender_theme(void) {
    return
        "# Calm Lavender -- the bundled default theme.\n"
        "name = \"calm-lavender\"\n"
        "display_name = \"Calm Lavender\"\n"
        "\n"
        "[colors]\n"
        "calm_purple  = \"#CBA6F7\"\n"
        "soft_blue    = \"#89B4FA\"\n"
        "gentle_pink  = \"#F5C2E7\"\n"
        "mint_green   = \"#A6E3A1\"\n"
        "warm_yellow  = \"#F9E2AF\"\n"
        "soft_red     = \"#F38BA8\"\n"
        "cloud_gray   = \"#BAC2DE\"\n"
        "\n"
        "[prompt]\n"
        "icon             = \"\xF0\x9F\x8C\x99\"\n"
        "border_color     = \"cloud_gray\"\n"
        "path_color       = \"soft_blue\"\n"
        "git_clean_color  = \"mint_green\"\n"
        "git_dirty_color  = \"soft_red\"\n"
        "arrow_color      = \"calm_purple\"\n"
        "\n"
        "# Whole-terminal colors -- picked up by `calm sync` for every synced\n"
        "# terminal emulator's background/foreground/cursor, and by Fastfetch's\n"
        "# generated color scheme. A palette key or a literal \"#RRGGBB\" both work.\n"
        "[terminal]\n"
        "background = \"#1B1823\"\n"
        "foreground = \"#E5E1F0\"\n"
        "cursor     = \"calm_purple\"\n";
}

/* Backs both ensure_scaffold() and scaffold_defaults() -- a single
 * source of truth for "every topic file scaffold.c owns, and what its
 * default content is", so `calm repair` restoring one corrupt file
 * can't drift out of sync with what a fresh install actually gets.
 *
 * Order matters here beyond readability: config.calm is deliberately
 * listed LAST. `calm_parse_file` follows `include` directives, so
 * parsing config.calm fails if *any* included topic file is broken --
 * not just if config.calm's own content is. `calm repair` walks this
 * table in order, so every included file gets validated/restored
 * first; by the time config.calm itself is checked, a failure there
 * really is config.calm's own fault, not a corrupt include bubbling
 * up and causing config.calm to be needlessly backed up and reset to
 * defaults over a typo in a completely different file. */
static const ScaffoldDefault SCAFFOLD_DEFAULTS[11] = {
    {environment_file, default_environment_calm, "environment.calm"},
    {directory_file, default_directory_calm, "directory.calm"},
    {history_settings_file, default_history_calm, "history.calm"},
    {keyboard_file, default_keyboard_calm, "keyboard.calm"},
    {terminal_file, default_terminal_calm, "terminal.calm"},
    {aliases_file, default_aliases_calm, "aliases.calm"},
    {functions_file, default_functions_calm, "functions.calm"},
    {plugins_state_file, default_plugins_calm, "plugins.calm"},
    {plugins_active_file, default_plugins_active_calm, "plugins_active.calm"},
    {profile_active_file, default_profile_active_calm, "profile_active.calm"},
    {config_file, default_config_calm, "config.calm"},
};

const ScaffoldDefault *scaffold_defaults(size_t *out_count) {
    if (out_count) {
        *out_count = sizeof(SCAFFOLD_DEFAULTS) / sizeof(SCAFFOLD_DEFAULTS[0]);
    }
    return SCAFFOLD_DEFAULTS;
}

/* One-time migration for installs scaffolded before the profile/plugin
 * systems existed: their config.calm has no `include
 * "plugins_active.calm"`/`include "profile_active.calm"` line, so a
 * plugin's or profile's overlay would silently never be read. Uses
 * the same idempotent append pattern fsutil's file_contains() is
 * meant for -- safe to call every run, a no-op once the line is
 * present.
 *
 * Known limitation: this always appends to the *end* of the file, so
 * an install that already migrated in profile_active.calm (from an
 * older calm-shell that had profiles but not yet plugins) will end up
 * with plugins_active.calm's include appearing *after*
 * profile_active.calm's -- inverting default_config_calm()'s intended
 * "profile wins over plugin" precedence for that one upgrade path. A
 * fresh scaffold (or any install migrating both at once, this
 * version's actual release) gets the right order. Reordering existing
 * include lines in place isn't worth the risk of mangling a config
 * file the user may have since hand-edited around either line. */
static bool migrate_generated_include(const char *cfg_path, const char *basename) {
    if (!path_is_file(cfg_path)) {
        return true; /* nothing to migrate -- default_config_calm() already has it */
    }
    if (file_contains(cfg_path, basename)) {
        return true;
    }
    char *addition = xsprintf("\n"
                               "# Added by a calm-shell upgrade: see default_config_calm() in\n"
                               "# config/scaffold.c for why this must stay last.\n"
                               "include \"%s\"\n",
                               basename);
    bool ok = append_to_file(cfg_path, addition);
    free(addition);
    return ok;
}

bool ensure_scaffold(void) {
    char *dirs[5] = {config_dir(), themes_dir(), plugins_dir(), history_dir(), profiles_dir()};
    bool ok = true;
    for (int i = 0; i < 5; i++) {
        if (!dirs[i] || !mkdir_recursive(dirs[i])) {
            ok = false;
        }
    }
    if (ok) {
        size_t count = 0;
        const ScaffoldDefault *defaults = scaffold_defaults(&count);
        for (size_t i = 0; i < count && ok; i++) {
            char *path = defaults[i].path_fn();
            if (!path || !write_file_if_missing(path, defaults[i].content_fn())) {
                ok = false;
            }
            free(path);
        }

        char *themes = themes_dir();
        if (themes) {
            char *lavender_path = join_path(themes, "calm-lavender.calm");
            write_file_if_missing(lavender_path, default_lavender_theme());
            free(lavender_path);
            free(themes);
        }

        char *cfg_path = config_file();
        if (cfg_path) {
            ok = migrate_generated_include(cfg_path, "plugins_active.calm") && ok;
            ok = migrate_generated_include(cfg_path, "profile_active.calm") && ok;
            free(cfg_path);
        }
    }
    for (int i = 0; i < 5; i++) {
        free(dirs[i]);
    }
    return ok;
}
