#include "term/emulator_sync.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "exec/process.h"
#include "theme/color_scheme.h"
#include "util/fsutil.h"
#include "util/strbuf.h"
#include "util/strutil.h"
#include "util/xalloc.h"

/* ---- small shared helpers ------------------------------------------- */

/* "#RRGGBB" -> "RRGGBB" (no leading '#'), for the formats (foot,
 * Konsole's decimal form aside) that want the hash omitted. Returns a
 * pointer into `hex` itself, not a new allocation. */
static const char *strip_hash(const char *hex) {
    return (hex[0] == '#') ? hex + 1 : hex;
}

static char *config_subdir(const char *app) {
    char *base = xdg_config_dir();
    if (!base) {
        return NULL;
    }
    char *out = join_path(base, app);
    free(base);
    return out;
}

/* Ensures `main_config_path` references `generated_path` via
 * `directive_line` (a complete, newline-terminated line). If the
 * generated filename already appears anywhere in the file, does
 * nothing (already wired, however the user or a previous sync phrased
 * it). If the file doesn't exist yet, creates it containing just that
 * line. Otherwise appends the line, preceded by a comment explaining
 * where it came from, to the end -- the existing content is never
 * touched. `comment_prefix` is that format's comment marker ("#",
 * "//", "--", ...). */
static bool ensure_include_line(const char *main_config_path, const char *generated_basename,
                                 const char *directive_line, const char *comment_prefix) {
    if (file_contains(main_config_path, generated_basename)) {
        return true;
    }
    if (!path_exists(main_config_path)) {
        return overwrite_file(main_config_path, directive_line);
    }
    char *addition = xsprintf("\n%s Added by calm-shell (`calm sync`) -- keeps this terminal's\n"
                               "%s theme matched to Calm-shell's active theme.\n%s",
                               comment_prefix, comment_prefix, directive_line);
    bool ok = append_to_file(main_config_path, addition);
    free(addition);
    return ok;
}

static const char *cursor_style_kitty(CursorStyle s) {
    switch (s) {
        case CURSOR_STYLE_BLOCK:
            return "block";
        case CURSOR_STYLE_UNDERLINE:
            return "underline";
        default:
            return "beam";
    }
}

static const char *cursor_style_ghostty(CursorStyle s) {
    switch (s) {
        case CURSOR_STYLE_BLOCK:
            return "block";
        case CURSOR_STYLE_UNDERLINE:
            return "underline";
        default:
            return "bar"; /* Ghostty's name for a beam/I-beam cursor. */
    }
}

/* ---- Kitty ------------------------------------------------------------
 * https://sw.kovidgoyal.net/kitty/conf/ -- `include` is a simple
 * relative-or-absolute directive kitty resolves at load time, so
 * wiring the generated file in is a single idempotent append. */

static bool sync_kitty(const Theme *theme, const TermAppearance *ap, char **out_detail) {
    char *dir = config_subdir("kitty");
    if (!dir || !mkdir_recursive(dir)) {
        free(dir);
        if (out_detail) {
            *out_detail = xstrdup("kitty: could not create ~/.config/kitty");
        }
        return false;
    }

    TermColorScheme cs;
    color_scheme_build(theme, &cs);

    StrBuf sb;
    strbuf_init(&sb);
    strbuf_append(&sb, "# Generated by calm-shell (`calm sync`) -- edits here are overwritten\n"
                        "# on the next sync. Change the active Calm-shell theme instead.\n\n");
    char *line = xsprintf("background %s\nforeground %s\ncursor %s\n\n", cs.background, cs.foreground, cs.cursor);
    strbuf_append(&sb, line);
    free(line);

    line = xsprintf("cursor_shape %s\ncursor_blink_interval %s\n\n", cursor_style_kitty(ap->cursor_style),
                     ap->cursor_blink ? "0.5" : "0");
    strbuf_append(&sb, line);
    free(line);

    line = xsprintf("background_opacity %.2f\n", ap->opacity);
    strbuf_append(&sb, line);
    free(line);
    line = xsprintf("window_padding_width %lld\n", ap->padding);
    strbuf_append(&sb, line);
    free(line);
    line = xsprintf("hide_window_decorations %s\n\n", ap->window_decorations ? "no" : "yes");
    strbuf_append(&sb, line);
    free(line);

    line = xsprintf("font_family %s\nfont_size %.1f\n\n", ap->font_family, ap->font_size);
    strbuf_append(&sb, line);
    free(line);

    for (int i = 0; i < 16; i++) {
        line = xsprintf("color%d %s\n", i, cs.ansi[i]);
        strbuf_append(&sb, line);
        free(line);
    }

    char *contents = strbuf_take(&sb);
    char *generated_path = join_path(dir, "calm-shell-theme.conf");
    bool wrote = overwrite_file(generated_path, contents);
    free(contents);

    bool wired = false;
    if (wrote) {
        char *main_conf = join_path(dir, "kitty.conf");
        char *directive = xsprintf("include %s\n", generated_path);
        wired = ensure_include_line(main_conf, "calm-shell-theme.conf", directive, "#");
        free(directive);
        free(main_conf);
    }

    if (out_detail) {
        *out_detail = wrote ? (wired ? xstrdup("kitty: theme synced (kitty.conf now includes calm-shell-theme.conf)")
                                      : xstrdup("kitty: wrote calm-shell-theme.conf, but could not update kitty.conf"))
                             : xstrdup("kitty: failed to write calm-shell-theme.conf");
    }

    color_scheme_free(&cs);
    free(generated_path);
    free(dir);
    return wrote;
}

/* ---- Alacritty ---------------------------------------------------------
 * Modern Alacritty (>=0.13) reads TOML and supports
 * `general.import = [...]`. Safely splicing a path into an *existing*
 * TOML array without a real TOML writer is fragile, so: if
 * alacritty.toml doesn't exist yet, we create it with the import;
 * if it exists and already has a `[general]` table, we leave it alone
 * and say so, rather than risk a duplicate-table TOML error. */

static bool sync_alacritty(const Theme *theme, const TermAppearance *ap, char **out_detail) {
    char *dir = config_subdir("alacritty");
    if (!dir || !mkdir_recursive(dir)) {
        free(dir);
        if (out_detail) {
            *out_detail = xstrdup("alacritty: could not create ~/.config/alacritty");
        }
        return false;
    }

    TermColorScheme cs;
    color_scheme_build(theme, &cs);

    StrBuf sb;
    strbuf_init(&sb);
    strbuf_append(&sb, "# Generated by calm-shell (`calm sync`) -- edits here are overwritten\n"
                        "# on the next sync. Change the active Calm-shell theme instead.\n\n");

    char *chunk = xsprintf("[colors.primary]\nbackground = \"%s\"\nforeground = \"%s\"\n\n"
                            "[colors.cursor]\ntext = \"%s\"\ncursor = \"%s\"\n\n",
                            cs.background, cs.foreground, cs.background, cs.cursor);
    strbuf_append(&sb, chunk);
    free(chunk);

    static const char *const names[8] = {"black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"};
    strbuf_append(&sb, "[colors.normal]\n");
    for (int i = 0; i < 8; i++) {
        chunk = xsprintf("%s = \"%s\"\n", names[i], cs.ansi[i]);
        strbuf_append(&sb, chunk);
        free(chunk);
    }
    strbuf_append(&sb, "\n[colors.bright]\n");
    for (int i = 0; i < 8; i++) {
        chunk = xsprintf("%s = \"%s\"\n", names[i], cs.ansi[8 + i]);
        strbuf_append(&sb, chunk);
        free(chunk);
    }

    chunk = xsprintf("\n[font]\nsize = %.1f\n\n[font.normal]\nfamily = \"%s\"\n\n", ap->font_size, ap->font_family);
    strbuf_append(&sb, chunk);
    free(chunk);

    chunk = xsprintf("[cursor]\nstyle = { shape = \"%s\", blinking = \"%s\" }\n\n",
                      ap->cursor_style == CURSOR_STYLE_BLOCK   ? "Block"
                      : ap->cursor_style == CURSOR_STYLE_UNDERLINE ? "Underline"
                                                                    : "Beam",
                      ap->cursor_blink ? "On" : "Off");
    strbuf_append(&sb, chunk);
    free(chunk);

    chunk = xsprintf("[window]\nopacity = %.2f\npadding = { x = %lld, y = %lld }\ndecorations = \"%s\"\n",
                      ap->opacity, ap->padding, ap->padding, ap->window_decorations ? "full" : "none");
    strbuf_append(&sb, chunk);
    free(chunk);

    char *contents = strbuf_take(&sb);
    char *generated_path = join_path(dir, "calm-shell-theme.toml");
    bool wrote = overwrite_file(generated_path, contents);
    free(contents);

    bool wired = false;
    bool needs_manual = false;
    if (wrote) {
        char *main_conf = join_path(dir, "alacritty.toml");
        if (file_contains(main_conf, "calm-shell-theme.toml")) {
            wired = true;
        } else if (!path_exists(main_conf)) {
            char *directive = xsprintf("[general]\nimport = [\"%s\"]\n", generated_path);
            wired = overwrite_file(main_conf, directive);
            free(directive);
        } else if (file_contains(main_conf, "[general]")) {
            /* A `[general]` table already exists -- don't risk a
             * second one. The generated file is still up to date;
             * the user (or `calm doctor`) just needs to add our path
             * to their existing `import` list once. */
            needs_manual = true;
        } else {
            char *addition = xsprintf("\n# Added by calm-shell (`calm sync`) -- keeps this terminal's\n"
                                       "# theme matched to Calm-shell's active theme.\n[general]\nimport = [\"%s\"]\n",
                                       generated_path);
            wired = append_to_file(main_conf, addition);
            free(addition);
        }
        free(main_conf);
    }

    if (out_detail) {
        if (!wrote) {
            *out_detail = xstrdup("alacritty: failed to write calm-shell-theme.toml");
        } else if (wired) {
            *out_detail = xstrdup("alacritty: theme synced (alacritty.toml now imports calm-shell-theme.toml)");
        } else if (needs_manual) {
            *out_detail = xsprintf(
                "alacritty: wrote calm-shell-theme.toml -- add \"%s/calm-shell-theme.toml\" to your existing "
                "[general] import list to finish wiring it in",
                dir);
        } else {
            *out_detail = xstrdup("alacritty: wrote calm-shell-theme.toml, but could not update alacritty.toml");
        }
    }

    color_scheme_free(&cs);
    free(generated_path);
    free(dir);
    return wrote;
}

/* ---- WezTerm ------------------------------------------------------------
 * wezterm.lua is a real Lua program, not declarative data -- there's
 * no single safe insertion point in an arbitrary existing one. We
 * always regenerate the data-only companion module; for a *fresh*
 * install with no wezterm.lua yet, we also generate one that loads
 * it. For an existing wezterm.lua, we leave it untouched and report
 * the two lines to add by hand. */

static bool sync_wezterm(const Theme *theme, const TermAppearance *ap, char **out_detail) {
    char *dir = config_subdir("wezterm");
    if (!dir || !mkdir_recursive(dir)) {
        free(dir);
        if (out_detail) {
            *out_detail = xstrdup("wezterm: could not create ~/.config/wezterm");
        }
        return false;
    }

    TermColorScheme cs;
    color_scheme_build(theme, &cs);

    StrBuf sb;
    strbuf_init(&sb);
    strbuf_append(&sb, "-- Generated by calm-shell (`calm sync`) -- edits here are overwritten\n"
                        "-- on the next sync. Change the active Calm-shell theme instead.\nreturn {\n"
                        "  colors = {\n");
    char *chunk = xsprintf("    background = \"%s\",\n    foreground = \"%s\",\n"
                            "    cursor_bg = \"%s\",\n    cursor_border = \"%s\",\n    cursor_fg = \"%s\",\n",
                            cs.background, cs.foreground, cs.cursor, cs.cursor, cs.background);
    strbuf_append(&sb, chunk);
    free(chunk);

    strbuf_append(&sb, "    ansi = {\n");
    for (int i = 0; i < 8; i++) {
        chunk = xsprintf("      \"%s\",\n", cs.ansi[i]);
        strbuf_append(&sb, chunk);
        free(chunk);
    }
    strbuf_append(&sb, "    },\n    brights = {\n");
    for (int i = 0; i < 8; i++) {
        chunk = xsprintf("      \"%s\",\n", cs.ansi[8 + i]);
        strbuf_append(&sb, chunk);
        free(chunk);
    }
    strbuf_append(&sb, "    },\n  },\n");

    chunk = xsprintf("  font_family = \"%s\",\n  font_size = %.1f,\n"
                      "  window_background_opacity = %.2f,\n"
                      "  window_padding = { left = %lld, right = %lld, top = %lld, bottom = %lld },\n"
                      "  window_decorations = \"%s\",\n"
                      "  default_cursor_style = \"%s%s\",\n",
                      ap->font_family, ap->font_size, ap->opacity, ap->padding, ap->padding, ap->padding, ap->padding,
                      ap->window_decorations ? "TITLE | RESIZE" : "NONE",
                      ap->cursor_blink ? "Blinking" : "Steady",
                      ap->cursor_style == CURSOR_STYLE_BLOCK   ? "Block"
                      : ap->cursor_style == CURSOR_STYLE_UNDERLINE ? "Underline"
                                                                    : "Bar");
    strbuf_append(&sb, chunk);
    free(chunk);
    strbuf_append(&sb, "}\n");

    char *contents = strbuf_take(&sb);
    char *generated_path = join_path(dir, "calm-shell-theme.lua");
    bool wrote = overwrite_file(generated_path, contents);
    free(contents);

    bool wired = false;
    bool needs_manual = false;
    char *main_conf = join_path(dir, "wezterm.lua");
    if (wrote) {
        if (file_contains(main_conf, "calm-shell-theme.lua")) {
            wired = true;
        } else if (!path_exists(main_conf)) {
            const char *bootstrap = "local wezterm = require 'wezterm'\n\n"
                                     "-- Loads calm-shell's generated theme/appearance table. Regenerated by\n"
                                     "-- `calm sync`; add your own settings below the merge if you like.\n"
                                     "local config = dofile(wezterm.config_dir .. '/calm-shell-theme.lua')\n\n"
                                     "return config\n";
            wired = overwrite_file(main_conf, bootstrap);
        } else {
            needs_manual = true;
        }
    }

    if (out_detail) {
        if (!wrote) {
            *out_detail = xstrdup("wezterm: failed to write calm-shell-theme.lua");
        } else if (wired) {
            *out_detail = xstrdup("wezterm: theme synced (wezterm.lua loads calm-shell-theme.lua)");
        } else if (needs_manual) {
            *out_detail =
                xstrdup("wezterm: wrote calm-shell-theme.lua -- merge `dofile(wezterm.config_dir .. "
                         "'/calm-shell-theme.lua')` into your existing wezterm.lua to finish wiring it in");
        } else {
            *out_detail = xstrdup("wezterm: wrote calm-shell-theme.lua, but could not create wezterm.lua");
        }
    }

    color_scheme_free(&cs);
    free(generated_path);
    free(main_conf);
    free(dir);
    return wrote;
}

/* ---- Foot --------------------------------------------------------------
 * foot.ini supports a top-level `include=<path>` directive (foot
 * >=1.14), so wiring works the same way as Kitty's `include`. Foot's
 * own hex colors are written without a leading '#'. */

static bool sync_foot(const Theme *theme, const TermAppearance *ap, char **out_detail) {
    char *dir = config_subdir("foot");
    if (!dir || !mkdir_recursive(dir)) {
        free(dir);
        if (out_detail) {
            *out_detail = xstrdup("foot: could not create ~/.config/foot");
        }
        return false;
    }

    TermColorScheme cs;
    color_scheme_build(theme, &cs);

    StrBuf sb;
    strbuf_init(&sb);
    strbuf_append(&sb, "# Generated by calm-shell (`calm sync`) -- edits here are overwritten\n"
                        "# on the next sync. Change the active Calm-shell theme instead.\n\n[main]\n");
    char *chunk = xsprintf("font=%s:size=%.0f\npad=%lldx%lld\n\n", ap->font_family, ap->font_size, ap->padding,
                            ap->padding);
    strbuf_append(&sb, chunk);
    free(chunk);

    chunk = xsprintf("[cursor]\nstyle=%s\nblink=%s\ncolor=%s %s\n\n", cursor_style_kitty(ap->cursor_style),
                      ap->cursor_blink ? "yes" : "no", strip_hash(cs.background), strip_hash(cs.cursor));
    strbuf_append(&sb, chunk);
    free(chunk);

    strbuf_append(&sb, "[colors]\n");
    chunk = xsprintf("background=%s\nforeground=%s\nalpha=%.2f\n\n", strip_hash(cs.background),
                      strip_hash(cs.foreground), ap->opacity);
    strbuf_append(&sb, chunk);
    free(chunk);
    for (int i = 0; i < 8; i++) {
        chunk = xsprintf("regular%d=%s\n", i, strip_hash(cs.ansi[i]));
        strbuf_append(&sb, chunk);
        free(chunk);
    }
    for (int i = 0; i < 8; i++) {
        chunk = xsprintf("bright%d=%s\n", i, strip_hash(cs.ansi[8 + i]));
        strbuf_append(&sb, chunk);
        free(chunk);
    }

    if (!ap->window_decorations) {
        /* Foot only draws its own decorations in CSD mode; zeroing
         * the border is the closest equivalent to "no decorations"
         * it exposes. Left alone (server-side/compositor default)
         * when decorations are wanted. */
        strbuf_append(&sb, "\n[csd]\nsize=0\nborder-width=0\n");
    }

    char *contents = strbuf_take(&sb);
    char *generated_path = join_path(dir, "calm-shell-theme.ini");
    bool wrote = overwrite_file(generated_path, contents);
    free(contents);

    bool wired = false;
    if (wrote) {
        char *main_conf = join_path(dir, "foot.ini");
        char *directive = xsprintf("include=%s\n", generated_path);
        wired = ensure_include_line(main_conf, "calm-shell-theme.ini", directive, "#");
        free(directive);
        free(main_conf);
    }

    if (out_detail) {
        *out_detail = wrote ? (wired ? xstrdup("foot: theme synced (foot.ini now includes calm-shell-theme.ini)")
                                      : xstrdup("foot: wrote calm-shell-theme.ini, but could not update foot.ini"))
                             : xstrdup("foot: failed to write calm-shell-theme.ini");
    }

    color_scheme_free(&cs);
    free(generated_path);
    free(dir);
    return wrote;
}

/* ---- Ghostty -------------------------------------------------------------
 * `config-file = <path>` pulls in another Ghostty config file, same
 * shape as Kitty's `include`. Ghostty colors are also written without
 * a leading '#', and its 16-slot palette is `palette = N=#RRGGBB`
 * (one repeated key, unlike everyone else's 16 separate keys). */

static bool sync_ghostty(const Theme *theme, const TermAppearance *ap, char **out_detail) {
    char *dir = config_subdir("ghostty");
    if (!dir || !mkdir_recursive(dir)) {
        free(dir);
        if (out_detail) {
            *out_detail = xstrdup("ghostty: could not create ~/.config/ghostty");
        }
        return false;
    }

    TermColorScheme cs;
    color_scheme_build(theme, &cs);

    StrBuf sb;
    strbuf_init(&sb);
    strbuf_append(&sb, "# Generated by calm-shell (`calm sync`) -- edits here are overwritten\n"
                        "# on the next sync. Change the active Calm-shell theme instead.\n\n");
    char *chunk = xsprintf("background = %s\nforeground = %s\ncursor-color = %s\n", strip_hash(cs.background),
                            strip_hash(cs.foreground), strip_hash(cs.cursor));
    strbuf_append(&sb, chunk);
    free(chunk);

    chunk = xsprintf("cursor-style = %s\ncursor-style-blink = %s\n", cursor_style_ghostty(ap->cursor_style),
                      ap->cursor_blink ? "true" : "false");
    strbuf_append(&sb, chunk);
    free(chunk);

    chunk = xsprintf("background-opacity = %.2f\nwindow-padding-x = %lld\nwindow-padding-y = %lld\n"
                      "window-decoration = %s\n",
                      ap->opacity, ap->padding, ap->padding, ap->window_decorations ? "true" : "false");
    strbuf_append(&sb, chunk);
    free(chunk);

    chunk = xsprintf("font-family = %s\nfont-size = %.0f\n\n", ap->font_family, ap->font_size);
    strbuf_append(&sb, chunk);
    free(chunk);

    for (int i = 0; i < 16; i++) {
        chunk = xsprintf("palette = %d=%s\n", i, strip_hash(cs.ansi[i]));
        strbuf_append(&sb, chunk);
        free(chunk);
    }

    char *contents = strbuf_take(&sb);
    char *generated_path = join_path(dir, "calm-shell-theme.conf");
    bool wrote = overwrite_file(generated_path, contents);
    free(contents);

    bool wired = false;
    if (wrote) {
        char *main_conf = join_path(dir, "config");
        char *directive = xsprintf("config-file = %s\n", generated_path);
        wired = ensure_include_line(main_conf, "calm-shell-theme.conf", directive, "#");
        free(directive);
        free(main_conf);
    }

    if (out_detail) {
        *out_detail =
            wrote ? (wired ? xstrdup("ghostty: theme synced (config now includes calm-shell-theme.conf)")
                           : xstrdup("ghostty: wrote calm-shell-theme.conf, but could not update the main config"))
                  : xstrdup("ghostty: failed to write calm-shell-theme.conf");
    }

    color_scheme_free(&cs);
    free(generated_path);
    free(dir);
    return wrote;
}

/* ---- Konsole -------------------------------------------------------------
 * Konsole has no single theme file: colors live in a `.colorscheme`
 * (decimal "r,g,b", not hex) under the data dir, and a profile picks
 * one up via its own `ColorScheme=` key. We always (re)write the
 * colorscheme; we only patch a profile if one already exists to patch
 * -- inventing a whole new, valid `.profile` from scratch risks
 * producing something Konsole rejects outright. */

static char *decimal_rgb(const Theme *theme, const char *hex) {
    unsigned int r, g, b;
    sscanf(strip_hash(hex), "%02x%02x%02x", &r, &g, &b);
    (void)theme;
    return xsprintf("%u,%u,%u", r, g, b);
}

static void append_konsole_color_section(StrBuf *sb, const char *section, const char *hex) {
    char *dec = decimal_rgb(NULL, hex);
    char *chunk = xsprintf("[%s]\nColor=%s\n\n", section, dec);
    strbuf_append(sb, chunk);
    free(chunk);
    free(dec);
}

/* Returns the value of `key=` under `[section]` in `ini_text` (a
 * whole already-read file), or NULL if either is missing. Caller must
 * free(). A small, deliberately forgiving INI reader -- good enough
 * for the handful of keys calm-shell reads out of Konsole's own files,
 * not a general-purpose parser. */
static char *ini_get(const char *ini_text, const char *section, const char *key) {
    if (!ini_text) {
        return NULL;
    }
    size_t line_count = 0;
    char **lines = split_lines(ini_text, &line_count);
    char *result = NULL;
    bool in_section = section[0] == '\0'; /* empty section = top of file */
    char *want_header = xsprintf("[%s]", section);
    size_t key_len = strlen(key);
    for (size_t i = 0; i < line_count && !result; i++) {
        char *trimmed = xstrdup(lines[i]);
        trim_in_place(trimmed);
        if (trimmed[0] == '[') {
            in_section = strcmp(trimmed, want_header) == 0;
        } else if (in_section && strncmp(trimmed, key, key_len) == 0 && trimmed[key_len] == '=') {
            result = xstrdup(trimmed + key_len + 1);
        }
        free(trimmed);
    }
    free(want_header);
    free_lines(lines, line_count);
    return result;
}

/* Replaces `key=`'s value under `[section]` in `ini_text` if present,
 * inserts a new `key=value` line right after the section header if
 * the section exists but the key doesn't, or appends a whole new
 * `[section]` block at the end if the section itself is missing.
 * Returns a newly allocated string; never mutates `ini_text`. */
static char *ini_set(const char *ini_text, const char *section, const char *key, const char *value) {
    size_t line_count = 0;
    char **lines = ini_text ? split_lines(ini_text, &line_count) : NULL;
    char *want_header = xsprintf("[%s]", section);
    size_t key_len = strlen(key);

    StrBuf out;
    strbuf_init(&out);
    bool in_section = false;
    bool section_found = false;
    bool key_written = false;
    for (size_t i = 0; i < line_count; i++) {
        char *trimmed = xstrdup(lines[i]);
        trim_in_place(trimmed);
        if (trimmed[0] == '[') {
            if (in_section && !key_written) {
                char *kv = xsprintf("%s=%s\n", key, value);
                strbuf_append(&out, kv);
                free(kv);
                key_written = true;
            }
            in_section = strcmp(trimmed, want_header) == 0;
            if (in_section) {
                section_found = true;
            }
            strbuf_append(&out, lines[i]);
            strbuf_append(&out, "\n");
        } else if (in_section && !key_written && strncmp(trimmed, key, key_len) == 0 && trimmed[key_len] == '=') {
            char *kv = xsprintf("%s=%s\n", key, value);
            strbuf_append(&out, kv);
            free(kv);
            key_written = true;
        } else {
            strbuf_append(&out, lines[i]);
            strbuf_append(&out, "\n");
        }
        free(trimmed);
    }
    if (in_section && !key_written) {
        char *kv = xsprintf("%s=%s\n", key, value);
        strbuf_append(&out, kv);
        free(kv);
        key_written = true;
    }
    if (!section_found) {
        char *block = xsprintf("[%s]\n%s=%s\n", section, key, value);
        strbuf_append(&out, block);
        free(block);
    }

    free(want_header);
    if (lines) {
        free_lines(lines, line_count);
    }
    return strbuf_take(&out);
}

static bool sync_konsole(const Theme *theme, const TermAppearance *ap, char **out_detail) {
    char *data_dir = xdg_data_dir();
    if (!data_dir) {
        if (out_detail) {
            *out_detail = xstrdup("konsole: could not resolve the XDG data directory");
        }
        return false;
    }
    char *konsole_data = join_path(data_dir, "konsole");
    free(data_dir);
    if (!mkdir_recursive(konsole_data)) {
        free(konsole_data);
        if (out_detail) {
            *out_detail = xstrdup("konsole: could not create ~/.local/share/konsole");
        }
        return false;
    }

    TermColorScheme cs;
    color_scheme_build(theme, &cs);

    StrBuf sb;
    strbuf_init(&sb);
    strbuf_append(&sb, "[General]\nDescription=Calm Shell\nOpacity=");
    char *op = xsprintf("%.2f\nWallpaper=\n\n", ap->opacity);
    strbuf_append(&sb, op);
    free(op);

    append_konsole_color_section(&sb, "Background", cs.ansi[0]);
    append_konsole_color_section(&sb, "BackgroundIntense", cs.ansi[8]);
    append_konsole_color_section(&sb, "Foreground", cs.ansi[7]);
    append_konsole_color_section(&sb, "ForegroundIntense", cs.ansi[15]);
    static const char *const slot_names[8] = {"Color0", "Color1", "Color2", "Color3",
                                               "Color4", "Color5", "Color6", "Color7"};
    for (int i = 0; i < 8; i++) {
        append_konsole_color_section(&sb, slot_names[i], cs.ansi[i]);
        char *intense_name = xsprintf("%sIntense", slot_names[i]);
        append_konsole_color_section(&sb, intense_name, cs.ansi[8 + i]);
        free(intense_name);
    }

    char *contents = strbuf_take(&sb);
    char *colorscheme_path = join_path(konsole_data, "CalmShell.colorscheme");
    bool wrote = overwrite_file(colorscheme_path, contents);
    free(contents);

    /* Best-effort: point the default profile at it, if we can find
     * one. Konsole's own default-profile pointer lives in
     * konsolerc's [Desktop Entry] section, in the user's *config*
     * dir (not the data dir the profile/colorscheme files live in). */
    bool profile_patched = false;
    bool profile_found = false;
    char *config_dir_path = xdg_config_dir();
    if (wrote && config_dir_path) {
        char *konsolerc_path = join_path(config_dir_path, "konsolerc");
        char *konsolerc = read_file_to_string(konsolerc_path);
        char *default_profile = ini_get(konsolerc, "Desktop Entry", "DefaultProfile");
        free(konsolerc);
        free(konsolerc_path);
        if (default_profile && default_profile[0] != '\0') {
            char *profile_path = join_path(konsole_data, default_profile);
            char *profile_text = read_file_to_string(profile_path);
            if (profile_text) {
                profile_found = true;
                char *patched = ini_set(profile_text, "Appearance", "ColorScheme", "CalmShell");
                profile_patched = overwrite_file(profile_path, patched);
                free(patched);
            }
            free(profile_text);
            free(profile_path);
        }
        free(default_profile);
    }
    free(config_dir_path);

    if (out_detail) {
        if (!wrote) {
            *out_detail = xstrdup("konsole: failed to write CalmShell.colorscheme");
        } else if (profile_patched) {
            *out_detail = xstrdup("konsole: theme synced (default profile now uses the CalmShell color scheme)");
        } else if (profile_found) {
            *out_detail = xstrdup("konsole: wrote CalmShell.colorscheme, but could not update the default profile");
        } else {
            *out_detail = xstrdup(
                "konsole: wrote CalmShell.colorscheme -- select it under Settings > Edit Current Profile > "
                "Appearance (no default profile found to update automatically)");
        }
    }

    color_scheme_free(&cs);
    free(colorscheme_path);
    free(konsole_data);
    return wrote;
}

/* ---- GNOME Terminal --------------------------------------------------
 * No config file at all -- everything lives in dconf, read and
 * written through `gsettings`. We resolve the default profile's UUID
 * once and then set each key directly on its
 * org.gnome.Terminal.Legacy.Profile relocatable schema instance. */

static char *gsettings_capture(const char *const argv[]) {
    return process_capture_stdout((char *const *)argv);
}

static bool gsettings_run(const char *const argv[]) {
    int status = -1;
    bool spawned = process_run_foreground((char *const *)argv, &status);
    return spawned && status == 0;
}

static bool sync_gnome_terminal(const Theme *theme, const TermAppearance *ap, char **out_detail) {
    if (!process_command_exists("gsettings")) {
        if (out_detail) {
            *out_detail = xstrdup("gnome-terminal: `gsettings` not found, skipping sync");
        }
        return false;
    }

    const char *get_default_argv[] = {"gsettings", "get", "org.gnome.Terminal.ProfilesList", "default", NULL};
    char *raw_uuid = gsettings_capture(get_default_argv);
    if (!raw_uuid) {
        if (out_detail) {
            *out_detail = xstrdup("gnome-terminal: could not read the default profile UUID");
        }
        return false;
    }
    trim_in_place(raw_uuid);
    /* gsettings prints GVariant strings single-quoted: 'uuid-here'. */
    char *uuid = raw_uuid;
    size_t len = strlen(uuid);
    if (len >= 2 && uuid[0] == '\'' && uuid[len - 1] == '\'') {
        uuid[len - 1] = '\0';
        uuid++;
    }

    char *schema = xsprintf("org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:%s/", uuid);
    free(raw_uuid);

    TermColorScheme cs;
    color_scheme_build(theme, &cs);

    StrBuf palette;
    strbuf_init(&palette);
    strbuf_append(&palette, "[");
    for (int i = 0; i < 16; i++) {
        char *item = xsprintf("%s'%s'", i == 0 ? "" : ", ", cs.ansi[i]);
        strbuf_append(&palette, item);
        free(item);
    }
    strbuf_append(&palette, "]");
    char *palette_value = strbuf_take(&palette);

    char *bg_value = xsprintf("'%s'", cs.background);
    char *fg_value = xsprintf("'%s'", cs.foreground);
    char *cursor_bg = xsprintf("'%s'", cs.cursor);
    char *cursor_fg = xsprintf("'%s'", cs.background);
    char *font_value = xsprintf("'%s %.0f'", ap->font_family, ap->font_size);
    int transparency_percent = (int)((1.0 - ap->opacity) * 100.0 + 0.5);
    char *transparency_value = xsprintf("%d", transparency_percent);
    const char *cursor_shape = ap->cursor_style == CURSOR_STYLE_BLOCK   ? "block"
                                : ap->cursor_style == CURSOR_STYLE_UNDERLINE ? "underline"
                                                                              : "ibeam";
    const char *blink_mode = ap->cursor_blink ? "on" : "off";
    bool transparent = ap->opacity < 1.0;

    struct {
        const char *key;
        const char *value;
    } settings[] = {
        {"use-theme-colors", "false"},
        {"background-color", bg_value},
        {"foreground-color", fg_value},
        {"palette", palette_value},
        {"bold-color-same-as-fg", "true"},
        {"cursor-colors-set", "true"},
        {"cursor-background-color", cursor_bg},
        {"cursor-foreground-color", cursor_fg},
        {"cursor-shape", cursor_shape},
        {"cursor-blink-mode", blink_mode},
        {"use-system-font", "false"},
        {"font", font_value},
        {"use-transparent-background", transparent ? "true" : "false"},
        {"background-transparency-percent", transparency_value},
    };

    bool all_ok = true;
    for (size_t i = 0; i < sizeof(settings) / sizeof(settings[0]); i++) {
        char *argv_schema = xsprintf("%s", schema); /* process_run_foreground's argv isn't const-correct upstream */
        const char *argv[] = {"gsettings", "set", argv_schema, settings[i].key, settings[i].value, NULL};
        if (!gsettings_run(argv)) {
            all_ok = false;
        }
        free(argv_schema);
    }

    if (out_detail) {
        *out_detail = all_ok
                          ? xstrdup("gnome-terminal: theme synced (default profile updated via gsettings)")
                          : xstrdup("gnome-terminal: synced most settings, but one or more `gsettings set` calls failed");
    }

    color_scheme_free(&cs);
    free(schema);
    free(palette_value);
    free(bg_value);
    free(fg_value);
    free(cursor_bg);
    free(cursor_fg);
    free(font_value);
    free(transparency_value);
    return all_ok;
}

/* ---- dispatch ---------------------------------------------------------- */

bool emulator_sync_write(TermEmulatorKind kind, const Theme *theme, const TermAppearance *appearance,
                          char **out_detail) {
    switch (kind) {
        case TERM_EMU_KITTY:
            return sync_kitty(theme, appearance, out_detail);
        case TERM_EMU_ALACRITTY:
            return sync_alacritty(theme, appearance, out_detail);
        case TERM_EMU_WEZTERM:
            return sync_wezterm(theme, appearance, out_detail);
        case TERM_EMU_FOOT:
            return sync_foot(theme, appearance, out_detail);
        case TERM_EMU_GHOSTTY:
            return sync_ghostty(theme, appearance, out_detail);
        case TERM_EMU_KONSOLE:
            return sync_konsole(theme, appearance, out_detail);
        case TERM_EMU_GNOME_TERMINAL:
            return sync_gnome_terminal(theme, appearance, out_detail);
        case TERM_EMU_UNKNOWN:
        default:
            if (out_detail) {
                *out_detail = xstrdup("no supported terminal emulator detected -- nothing synced");
            }
            return true;
    }
}
